### ISSUE TITLE
Issue with screenshots becoming blacked out

### ISSUE THREAD

**Issue by GadgetGabe** [MiXenia/Charm-List-Image-Transcriber-MHGU#3]
I ran into an issue where after I've placed all of my images in Input, when ran through the tool, all the images become completely blank, and the tool doesn't pick up what the charms are. The way I moved the images to my computer was by sending them to my phone and then attaching them to a word doc, then downloading them. Perhaps my method of moving them to my computer is the issue. They were saved as JPEGs by default although when I opened the screenshots in photos, the text was on the charm pages looked unaffected. I did not edit the cropping of the images in any way.

![FA04F5F3-500F-4E9F-B89E-B98DCCEF1C2E](https://user-images.githubusercontent.com/104158342/164508373-203f30e3-8a17-4bdb-80a5-9efffe6a91f2.jpeg)
![0E9E8BBB-B687-48D2-BE26-7D9BCA63A88E](https://user-images.githubusercontent.com/104158342/164508385-42ffa2d6-3039-479c-8c98-4d233e087df0.jpeg)

**Comment by MiXenia** [comment]
Can you zip up the images you used so I can compare them to the ones I used for testing?

**Comment by GadgetGabe** [comment]
[GadgetGabeCL.zip](https://github.com/MiXenia/Charm-List-Image-Transcriber-MHGU/files/8533463/GadgetGabeCL.zip)

**Comment by MiXenia** [comment]
It looks like the way that you transferred the images to your computer shrank and compressed them and the program wasn't originally able to handle that. I'm putting out a fix that will stretch the image but do note that it's not going to be able to read the text on the image well, so you'll get interesting results like this:

![fix quote unquote](https://user-images.githubusercontent.com/64364290/164531485-390ca2ab-5f9e-45aa-b80e-67c9a77dfb0a.png)

Hopefully it's not too tedious to correct the images! If it is, please try transferring them to your computer in a way that won't compress the images! 😸
